# Generated by Django 5.2.1 on 2025-05-31 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_lname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('stuent_lname', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.classes')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_class_subject',
            fields=[
                ('teacher_class_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.classes')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subjects')),
                ('teaccer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'absent'), ('p', 'present'), ('l', 'late')], max_length=1)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='attendance/images/')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.classes')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teachers')),
            ],
        ),
    ]
