# Generated by Django 5.2.1 on 2025-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_testmodel_alter_students_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
