# Generated by Django 5.2.1 on 2025-06-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_students_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_class_subject',
            old_name='teaccer_id',
            new_name='teacher_id',
        ),
    ]
