# Generated by Django 5.2.1 on 2025-06-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_teaccer_id_teacher_class_subject_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='stuent_lname',
            new_name='student_lname',
        ),
    ]
