# Generated by Django 5.2.1 on 2025-06-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_attendance_date_alter_attendance_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='proof_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
