# Generated by Django 5.2.1 on 2025-06-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
